version: '3.8'

services:
  mysql:
    container_name: wordpress-mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: wordpress
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - wp-net

  wordpress:
    container_name: wordpress
    image: wordpress:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: wordpress-mysql:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: my-secret-pw
    depends_on:
      - mysql
    networks:
      - wp-net

volumes:
  mysql-data:

networks:
  wp-net:
